config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get 'navigations/index'
  get 'navigations/dated'
  get 'navigations/suscribed'
  get 'navigations/unread'
  get 'navigations/owner'
  get 'navigations/nav'
  get 'navigations/show_object/:oid/:obj', to: 'navigations#show_object', as: :show_object

  devise_for :users, 
              controllers: {sessions: 'users/sessions', 
                            registrations: 'users/registrations', 
                            confirmations: 'users/confirmations',
                            passwords: 'users/passwords' }
  resources :users do
    resources :roles, only: [:create, :destroy]
  end

  as :user do
    delete 'users/:id', to: 'users#destroy', as: :admin_destroy_user
    get 'users/:user_id/new_role', to: 'users#new_role', as: :admin_new_user_role
    delete 'users/:id/role/:role_id', to: 'users#destroy_role', as: :admin_destroy_user_role
    post 'users/populate_resources', to: "users#resources_for_type"
    post 'users/create_role/:id', to: "users#create_role", as: :admin_create_user_role
    post 'users/send_confirmation', to: 'users#send_confirmation_again', as: :send_user_confirmation
    post 'users/exist_confirmed', to: 'users#exist_confirmed', as: :user_exist_confirmed
  end

  resources :categories do
    resources :subjects do
      resources :articles
    end
  end

  resources :subjects do
    resources :articles
  end

  resources :articles, shallow: true

  get '/subjects/subject_parent/:parent_id/new', to: 'subjects#new', as: :new_subject_child
  get '/subjects/subject_parent/:parent_id/category/:category_id/new', to: 'subjects#new', as: :new_subject_child_category
  get "/articles/news/index", to: 'articles#fresh_index', 
                              as: "news_articles"
  post "/article/:id/:online",to: 'articles#publication', 
                              as: 'online_article'
  post "/subject/:id/:online",to: 'subjects#publication',
                              as: 'online_subject'
  get 'tags/:tag', to: 'articles#index', as: :tag

end

app/views/users/profil/admin/_options_for_resources.html.haml
%option{value: ""}
= resources.each do |r|
  %option{value: "#{r[0]}"}= r[1]

app/views/users/profil/admin/_role.html.haml
.card.mb-3{style: "background-color: #090909;", id: "user_#{user.id}"}
  - if status == "edit"
    - color = "#111"
    - if user == current_user
      - color = "#191" 
    .card-title{style: "background-color: #{color}; padding: 5px;"}
      %b= user.username
      = " (#{user.second_name} #{user.familly_name})"
      .butt= link_to t("delete_account"), admin_destroy_user_path(user), 
        data: { confirm: "Voulez-vous clore le compte de #{user.username} ?" },
        method: :delete, class: "btn btn-sm btn-danger", remote: true
      .butt= link_to t("new_user_role"), admin_new_user_role_path(user.id),
        class: "btn btn-sm btn-primary",
        method: :get, remote: true
  %br
  - if user.roles.empty?
    .card-body= "Nothing"
  -else
    .card-body
      = render partial: "users/profil/user_roles", 
              locals: { user: user, status: "edit" }

app/views/users/profil/admin/_role_fields.html.haml
.modal-header
  %h5.modal-title
    = t("new_role")
  %button{type: "button", class: "close", 
          "data-dismiss": "modal", "aria-label": "Close"}
    %span{"aria-hidden": "true"}
= simple_form_for user, url: admin_create_user_role_path(user.id), 
                        method: :post, remote: true do |u|
  .modal-body
    = simple_fields_for :roles do |r|
      .col-4= r.input :name, label: "Role", as: :select, 
        collection: Role.distinct.pluck(:name).collect{ |name| [name, name] }
      .col-4
        = r.input :resource_type, label: "Type", as: :select,
          collection: ['Category', 'Subject', 'Article']
      .col-4
        = r.input :resource_id, label: "Name", as: :select,
          id: 'resource_name'
  .modal-footer
    .actions
      .butt= u.button :submit, t('create_role', username: user.username) ,class: "btn-success btn-sm"
      = render partial: "layouts/admin/cancel"

app/views/users/profil/admin/_roles.html.haml
- User.all.each do |user|
  = render partial: "users/profil/admin/role", locals: { user: user, status: "edit" }