config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get 'navigations/index'
  get 'navigations/dated'
  get 'navigations/suscribed'
  get 'navigations/unread'
  get 'navigations/owner'
  get 'navigations/nav'
  get 'navigations/show_object/:oid/:obj', to: 'navigations#show_object', as: :show_object

  devise_for :users, 
              controllers: {sessions: 'users/sessions', 
                            registrations: 'users/registrations', 
                            confirmations: 'users/confirmations',
                            passwords: 'users/passwords' }
  resources :users do
    resources :roles, only: [:create, :destroy]
  end

  as :user do
    delete 'users/:id', to: 'users#destroy', as: :admin_destroy_user
    get 'users/:user_id/new_role', to: 'users#new_role', as: :admin_new_user_role
    delete 'users/:id/role/:role_id', to: 'users#destroy_role', as: :admin_destroy_user_role
    post 'users/populate_resources', to: "users#resources_for_type"
    post 'users/create_role/:id', to: "users#create_role", as: :admin_create_user_role
    post 'users/send_confirmation', to: 'users#send_confirmation_again', as: :send_user_confirmation
    post 'users/exist_confirmed', to: 'users#exist_confirmed', as: :user_exist_confirmed
  end

  resources :categories do
    resources :subjects do
      resources :articles
    end
  end

  resources :subjects do
    resources :articles
  end

  resources :articles, shallow: true

  get '/subjects/subject_parent/:parent_id/new', to: 'subjects#new', as: :new_subject_child
  get '/subjects/subject_parent/:parent_id/category/:category_id/new', to: 'subjects#new', as: :new_subject_child_category
  get "/articles/news/index", to: 'articles#fresh_index', 
                              as: "news_articles"
  post "/article/:id/:online",to: 'articles#publication', 
                              as: 'online_article'
  post "/subject/:id/:online",to: 'subjects#publication',
                              as: 'online_subject'
  get 'tags/:tag', to: 'articles#index', as: :tag

end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  def index
  end

  def show_object
    if params[:obj] == 'category'
      @category = Category.find(params[:oid])
      render partial: "navigations/show/content_category", object: @category
    elsif params[:obj] == 'subject'
      @subject = Subject.find(params[:oid])
      render partial: "navigations/show/content_subject", object: @subject
    elsif params[:obj] == 'article'
      @article = Article.find(params[:oid])
      render partial: "navigations/show/content_article", object: @article
    end
  end
  
  def dated
  end

  def suscribed
  end

  def unread
  end

  def owner
  end

  def nav
    @categories = Category.all()
    data = list_categories(@categories)
    render json: data
  end

  private

  def list_categories(categories)
    data = []
    categories.each do |category|
      cid = category.id.to_s + "C"
      data << { id: cid, parent: "#", text: category.name.to_s, 
                state: { opened: true }, type: "category", 
                a_attr: { style: 'color: rgb(0,99,73);'} }
      list_subjects(category.subjects, cid, data)
    end 
    puts data
    return data
  end

  def list_subjects(subjects, pid, data)
    if (user_signed_in?) && (current_user.has_role? :admin)
      view_subjects = subjects.all
    else
      view_subjects = subjects.publishable_only
    end
    view_subjects.each do |subject|
      sid = subject.id.to_s + "S"
      parent_id = subject.parent_id.nil? ? pid 
                : subject.parent_id.to_s + "S"
      data << { id: sid, parent: parent_id, text: subject.title.to_s, 
                state: { opened: true }, type: "subject", 
                a_attr: { style: 'color: rgb(0,D0,23);'} }
      list_articles(subject.articles, sid, data)
    end
  end

  def list_articles(articles, pid, data)
    articles.each do |article|
      aid = article.id.to_s + "A"
      data << { id: aid, parent: pid, text: article.title.to_s, 
                state: { opened: true }, type: "article", 
                a_attr: { style: 'color: rgb(169,76,23);'} }
    end
  end

end

app/helpers/navigations_helper.rb
module NavigationsHelper
end

app/views/navigations/show/_content_article.haml
.row
  %h1.title
    = link_to @article.title, article_path(@article)
    .badge.badge-primary Article
.row
  = render partial: 'articles/show/description', object: @article
  = render partial: 'articles/show/links', object: @article

app/views/navigations/show/_content_category.haml
.row
  %h1.title
    = link_to @category.name, category_path(@category)
    .badge.badge-primary Catégorie
.row
  = render partial: 'categories/show/description', object: @category
  = render partial: 'categories/show/links', object: @category

app/views/navigations/show/_content_resource.haml
.row
  %h1.title
    = link_to title, category_path(resource)
    .badge.badge-primary= badge
.row
  = render partial: resource_partial_description, object: resource
  = render partial: resource_partial_links, object: resource

app/views/navigations/show/_content_subject.haml
.row
  %h1.title
    = link_to @subject.title, subject_path(@subject)
    .badge.badge-primary Sujet
.row
  = render partial: 'subjects/show/description', object: @subject
  = render partial: 'subjects/show/links', object: @subject