config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get 'navigations/index'
  get 'navigations/dated'
  get 'navigations/suscribed'
  get 'navigations/unread'
  get 'navigations/owner'
  get 'navigations/nav'
  get 'navigations/show_object/:oid/:obj', to: 'navigations#show_object', as: :show_object

  devise_for :users, 
              controllers: {sessions: 'users/sessions', 
                            registrations: 'users/registrations', 
                            confirmations: 'users/confirmations',
                            passwords: 'users/passwords' }
  resources :users do
    resources :roles, only: [:create, :destroy]
  end

  as :user do
    delete 'users/:id', to: 'users#destroy', as: :admin_destroy_user
    get 'users/:user_id/new_role', to: 'users#new_role', as: :admin_new_user_role
    delete 'users/:id/role/:role_id', to: 'users#destroy_role', as: :admin_destroy_user_role
    post 'users/populate_resources', to: "users#resources_for_type"
    post 'users/create_role/:id', to: "users#create_role", as: :admin_create_user_role
    post 'users/send_confirmation', to: 'users#send_confirmation_again', as: :send_user_confirmation
    post 'users/exist_confirmed', to: 'users#exist_confirmed', as: :user_exist_confirmed
  end

  resources :categories do
    resources :subjects do
      resources :articles
    end
  end

  resources :subjects do
    resources :articles
  end

  resources :articles, shallow: true

  get '/subjects/subject_parent/:parent_id/new', to: 'subjects#new', as: :new_subject_child
  get '/subjects/subject_parent/:parent_id/category/:category_id/new', to: 'subjects#new', as: :new_subject_child_category
  get "/articles/news/index", to: 'articles#fresh_index', 
                              as: "news_articles"
  post "/article/:id/:online",to: 'articles#publication', 
                              as: 'online_article'
  post "/subject/:id/:online",to: 'subjects#publication',
                              as: 'online_subject'
  get 'tags/:tag', to: 'articles#index', as: :tag

end

app/models/article.rb
class Article < ApplicationRecord
  resourcify
  paginates_per 10
  acts_as_ordered_taggable_on :interests
  belongs_to :subject
  has_one_attached :logo
  belongs_to :user, inverse_of: :articles

  validates :user_id, presence: true
  validates :subject, presence: true
  validates :title, presence: true,
                    length: { maximum: 42, minimum: 3 },
                    uniqueness: { scope: :subject,
                                  message: "unique for each subject" }

  scope :published_only, -> { where "published_at IS NOT NULL" }
  scope :blacklisted_ids, -> (ids) { where.not(subject_id: ids) }

  def self.preferences_list(user)

  end

  def self.publishable_subjects_only
    unpublished_and_child = []
    Subject.where(published_at: nil).each { |a|
      unpublished_and_child += a.self_and_descendants.ids }
    blacklisted_ids(unpublished_and_child.uniq)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  authorize_resource
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :login_required, only: [:new, :create, :edit, :update, :destroy]

  def fresh_index
    if !user_signed_in?
      if !params.has_key?(:date)
        @articles = Article.where("updated_at > ?", 1.week.ago)
                           .order(id: :asc)
      end
    end
    @articles = Article.where("updated_at > ?", 1.week.ago)
                       .publishable_subjects_only
                       .published_only
                       .order(id: :asc)
  end

  def index
    if helpers.administrator?
      @articles = Article.all.order(id: :asc)
      #@article = Article.new
    else
      @articles = Article.where.not(published_at: nil)
                         .order(id: :asc)
                         .publishable_subjects_only
    end
    if params[:tag]
      @articles = @articles.tagged_with(params[:tag])
    end
    @articles = @articles.page(params[:page]).per(10)
    if @articles.count == 0
      @articles = @articles.page(params[:page].to_i - 1).per(10)
    end
    respond_to do |format|
      format.js { render layout: false }
      format.html 
      format.json 
    end
  end

  def publication   # POST  :online == "yes" ? DateTime.now : null
    @article = Article.find(params[:id])
    @title = params[:title]
    if params.has_key?(:online)
    @article.published_at = params[:online] == "yes" ? DateTime.current : nil
    end
    gon.data = @article
    respond_to do |f|
      if @article.update(id:            params[:id], 
                         published_at:  @article.published_at)
        f.js { render layout: false }
        f.html { redirect_to controller: params[:k], 
                             action:     params[:a],
                             notice:     'Article has been pusblished' }
      else
        f.html { redirect_to controller: params[:k], 
                             action:     params[:a],
                             status:     'Article failed to be pusblished' }
      end
    end
  end

  def show
    if !@article.present?
      redirect_to articles_url, 
                  notice: "Article doesn't exist or is not published"
    end
  end

  def new
    @subject_disabled = false
    @title = "Create"
    @article = Article.new
    @article.user_id = current_user.id
    if !params[:subject_id].nil?
      @article.subject_id = params[:subject_id]
      @subject_disabled = true
      @title += " child"
    end
  end

  def edit
    @subject_disabled = false
    @title = "Edit"
    respond_to do |format|
      format.js { render layout: false }
      format.html
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if params.has_key?(:create_and_publish)
      @article.published_at = DateTime.current
    end
    respond_to do |format|
      if @result = @article.save
        format.js { render layout: false }
        format.html { 
          redirect_to @article, 
                      notice: 'Article was successfully created.' }
        format.json { 
          render :show, 
                 status: :created, 
                 location: @article }
      else
        gon.data = @article
        format.js { render layout: false }
        format.html { render :new }
        format.json { 
          render json: @article.errors, 
                 status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.js { render layout: false }
        format.html { 
          redirect_to @article, 
                       notice: 'Article was successfully updated.' }
        format.json 
      else
        gon.data = @article
        format.html { render :edit }
        format.json { 
          render json: @article.errors, 
                 status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @article.destroy
        format.js { render layout: false }
        format.html { 
          redirect_to articles_url, 
                      notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      else
        gon.data = @article
      end
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
      if !helpers.administrator? && 
         !helpers.can_publish_article?(@article)
        @article = nil
      end
    end

    def article_params
      params.require(:article).permit(:title, :description, :content, 
                                      :logo, :subject_id, :user_id,
                                      :published_at, :restricted, :private,
                                      :interest_list, :_destroy ,
                                      interests_attributes: [:id, :name, 
                                                             :taggings_count, 
                                                             :_destroy])
    end

    def login_required
      if !user_signed_in?
        redirect_to articles_url, alert: "You have to login first for this action."
      end
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def get_article_color(a)
    a.published_at.nil? ? 
      "red" : 
      !can_publish_subjects?(a.subject) ? 
        "orange" : 
        "green"
  end

  def selected_articles(articles)
    articles.published_only.reject{ |a| !can_publish_subjects?(a.subject) }
  end
end

app/views/articles/show/_description.haml
.col-3.col-sm-3
  .image{ style: "margin-top: 20px"}
    - if @article.logo.attached?
      = link_to image_tag(@article.logo.variant(resize: '400x400^'), 
                          alt: @article.title, 
                          class: 'img-fluid'), 
                article_path(@article.id), target: '_blank'
    - else
      %p No images for this article
.col-6.col-sm-4{:style => "padding-right: 10%;"}
  %p
    .label Description :
    .description.well= @article.description.html_safe
  - if @article.restricted
    %p.restricted= "restricted"
  - if @article.private
    %p.private= "private"
  .interests
    %table
      %tbody
        %tr
          %td Tags
          %td
            - for tag in @article.interest_list do
              .badge.badge-info= link_to tag, tag_path(tag)
  - if !current_user.nil?
    - if @article.published_at.nil?
      %p{style: "color: red;"} unpublished
    - else
      %p{style: "color: green;"} published

app/views/articles/show/_index_table.html.haml
%div
  - width_actions = administrator? ? "220px" : "50px"
  - if administrator?
    %p.nb Les titres des articles sont colorés: en rouge lorsqu'ils ne sont pas publiés, en orange lorsqu'il ne le sont pas du fait d'un de son sujet n'étant pas publié et en vert dans le cas contraire.
  %table
    %thead
      %tr.table-title
        %th Titres
        %th Logos
        %th Descriptions
        - if mode == "index"
          %th= "Sujet Lié"
          %th= "Catégories"
        - if administrator?
          %th.center{width: "#{width_actions}"}= "Actions"
    %tbody{id: "table_index_body"}
      - for article in articles
        %tr.index-column{id: "article_#{article.id}_row"}
          = render partial: "articles/show/index_table_row", 
                  locals: { article: article, mode: mode }

app/views/articles/show/_index_table_row.html.haml
- color = get_article_color(article)
- if administrator? || !article.published_at.nil?
  %td
    = link_to article.title, article_path(article.id), style: "color: #{color}"
  %td
    - if article.logo.attached?
      = image_tag article.logo.variant(resize: "50x25")
    - else
      = ""
  %td= article.description
  - if mode == "index"
    %td
      -if !article.subject.nil? 
        = link_to article.subject.title, subject_path(article.subject.id) 
      - else
        = ""
    %td
      - if !article.subject.category.nil?
        = link_to article.subject.category.name, category_path(article.subject.category.id)
      - else
        = ""
      - if administrator?
        %td.center
          = render partial: 'articles/form/form_links', 
                        locals: { article: article, title: "Edit", mode: "index" }
          .butt= button_to t('edit'), edit_article_path(article), 
                    method: "get", class: "btn btn-xs btn-outline-warning",
                    remote: true, 
                    "data-toggle": "modal", "data-target": ".dialog_action_article"
          .butt= button_to t('delete'), article, 
                    method: :delete, data: { confirm: 'Are you sure?' }, 
                    class: "btn btn-xs btn-outline-danger",
                    remote: true

app/views/articles/show/_links.haml
.col-3.col.sm-2
  - if user_signed_in?
    - if current_user.has_role? :admin
      .butt
        = button_to "Éditer l'article", edit_article_path(@article), 
                    { remote: true,
                    "data-toggle": "modal", "data-target": ".dialog_action_article",
                    method: :get, class: "btn btn-sm btn-warning" }
        = button_to "Supprimer l'article", @article, 
                    { method: :delete, data: { confirm: 'êtes vous sûre ?' },
                    remote: true, 
                    class: "btn btn-sm btn-danger" }

app/views/articles/show/_title.html.haml
.render
  - if status == "edit"
    = truncate article.title, length: 23
    .badge.badge-warning Article Edition
  - elsif status == "new"
    = t('article')
    .badge.badge-danger= t('create')
  - elsif status == "show"
    = truncate article.title, length: 23
    .badge.badge-secondary= t('article')
  - elsif status == "index"
    = t("articles")
    .badge.badge-dark= "Index #{article.count}" 
  - elsif status == "fresh_index"
    = t("last_publications")
    .badge.badge-success= "#{article.count} Nouveaux"